name: Docker Image Publish

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Deploy the Docker image to GitHub Package Registry (latest tag)
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: fooooooooooooooo/docker-bind/docker-bind
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
