name: Docker Image Publish

on: [push]

jobs:
  push-image:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "."
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@main

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: "Build Image"
        run: |
          docker build . --tag ghcr.io/fooooooooooooooo/docker-bind:latest
          docker push ghcr.io/fooooooooooooooo/docker-bind:latest
